name: Ubuntu CI

on: push

defaults:
  run:
    shell: bash

jobs:
  CI:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
      
    steps:
    - name: Install Libraries 
      run:  |
        sudo apt install build-essential                                    # Install GNU compilers.
        sudo apt install libboost-all-dev                                   # Install boost libraries.
        
    - name: Install GTest
      run:  |
        cd /tmp/
        git clone https://github.com/google/googletest.git -b v1.14.0       # Clone project from github to a specific release.
        cd googletest                                                       # Main directory of the cloned repository.
        mkdir build                                                         # Create a directory to hold the build output.
        cd build                                                            # Change current dir to build dir.
        cmake ..                                                            # Generate native build scripts for GoogleTest.
        make                                                                # Compile gtest
        sudo make install                                                   # Install in /usr/local/ by default

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Unit Tests
      run: |
        chmod -R 777 ${{ github.workspace }}/tests/scripts/
        ${{ github.workspace }}/tests/scripts/build.sh

    - name: Run Unit Tests
      run: |       
        chmod -R 777 ${{ github.workspace }}/tests/scripts/
        ${{ github.workspace }}/tests/scripts/run.sh
